//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/hadronomy/repos/ram/libs/core/core/Parser/MemoryMachineAssembly.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MemoryMachine.Core.Parser {
#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MemoryMachineAssemblyParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IMemoryMachineAssemblyVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MemoryMachineAssemblyParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] MemoryMachineAssemblyParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MemoryMachineAssemblyParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] MemoryMachineAssemblyParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MemoryMachineAssemblyParser.label_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel_definition([NotNull] MemoryMachineAssemblyParser.Label_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MemoryMachineAssemblyParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabel([NotNull] MemoryMachineAssemblyParser.LabelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MemoryMachineAssemblyParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] MemoryMachineAssemblyParser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>NumberOperand</c>
	/// labeled alternative in <see cref="MemoryMachineAssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberOperand([NotNull] MemoryMachineAssemblyParser.NumberOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IndirectOperand</c>
	/// labeled alternative in <see cref="MemoryMachineAssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndirectOperand([NotNull] MemoryMachineAssemblyParser.IndirectOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ImmediateOperand</c>
	/// labeled alternative in <see cref="MemoryMachineAssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImmediateOperand([NotNull] MemoryMachineAssemblyParser.ImmediateOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LabelOperand</c>
	/// labeled alternative in <see cref="MemoryMachineAssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabelOperand([NotNull] MemoryMachineAssemblyParser.LabelOperandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MemoryMachineAssemblyParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComment([NotNull] MemoryMachineAssemblyParser.CommentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MemoryMachineAssemblyParser.direct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDirect([NotNull] MemoryMachineAssemblyParser.DirectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MemoryMachineAssemblyParser.indirect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndirect([NotNull] MemoryMachineAssemblyParser.IndirectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MemoryMachineAssemblyParser.immediate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImmediate([NotNull] MemoryMachineAssemblyParser.ImmediateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MemoryMachineAssemblyParser.accessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAccessor([NotNull] MemoryMachineAssemblyParser.AccessorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MemoryMachineAssemblyParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex([NotNull] MemoryMachineAssemblyParser.IndexContext context);
}
} // namespace MemoryMachine.Core.Parser
