//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/hadronomy/practicas/PR2-DAA-2425/src/MemoryMachine.Core/Parser/MemoryMachineAssembly.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MemoryMachine.Core.Parser {
#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="MemoryMachineAssemblyParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IMemoryMachineAssemblyListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MemoryMachineAssemblyParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] MemoryMachineAssemblyParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MemoryMachineAssemblyParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] MemoryMachineAssemblyParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MemoryMachineAssemblyParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] MemoryMachineAssemblyParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MemoryMachineAssemblyParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] MemoryMachineAssemblyParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MemoryMachineAssemblyParser.label_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel_definition([NotNull] MemoryMachineAssemblyParser.Label_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MemoryMachineAssemblyParser.label_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel_definition([NotNull] MemoryMachineAssemblyParser.Label_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MemoryMachineAssemblyParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] MemoryMachineAssemblyParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MemoryMachineAssemblyParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] MemoryMachineAssemblyParser.LabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MemoryMachineAssemblyParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] MemoryMachineAssemblyParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MemoryMachineAssemblyParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] MemoryMachineAssemblyParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberOperand</c>
	/// labeled alternative in <see cref="MemoryMachineAssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberOperand([NotNull] MemoryMachineAssemblyParser.NumberOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberOperand</c>
	/// labeled alternative in <see cref="MemoryMachineAssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberOperand([NotNull] MemoryMachineAssemblyParser.NumberOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>IndirectOperand</c>
	/// labeled alternative in <see cref="MemoryMachineAssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndirectOperand([NotNull] MemoryMachineAssemblyParser.IndirectOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>IndirectOperand</c>
	/// labeled alternative in <see cref="MemoryMachineAssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndirectOperand([NotNull] MemoryMachineAssemblyParser.IndirectOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ImmediateOperand</c>
	/// labeled alternative in <see cref="MemoryMachineAssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImmediateOperand([NotNull] MemoryMachineAssemblyParser.ImmediateOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ImmediateOperand</c>
	/// labeled alternative in <see cref="MemoryMachineAssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImmediateOperand([NotNull] MemoryMachineAssemblyParser.ImmediateOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LabelOperand</c>
	/// labeled alternative in <see cref="MemoryMachineAssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabelOperand([NotNull] MemoryMachineAssemblyParser.LabelOperandContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LabelOperand</c>
	/// labeled alternative in <see cref="MemoryMachineAssemblyParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabelOperand([NotNull] MemoryMachineAssemblyParser.LabelOperandContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MemoryMachineAssemblyParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] MemoryMachineAssemblyParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MemoryMachineAssemblyParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] MemoryMachineAssemblyParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MemoryMachineAssemblyParser.direct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDirect([NotNull] MemoryMachineAssemblyParser.DirectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MemoryMachineAssemblyParser.direct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDirect([NotNull] MemoryMachineAssemblyParser.DirectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MemoryMachineAssemblyParser.indirect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndirect([NotNull] MemoryMachineAssemblyParser.IndirectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MemoryMachineAssemblyParser.indirect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndirect([NotNull] MemoryMachineAssemblyParser.IndirectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MemoryMachineAssemblyParser.immediate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImmediate([NotNull] MemoryMachineAssemblyParser.ImmediateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MemoryMachineAssemblyParser.immediate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImmediate([NotNull] MemoryMachineAssemblyParser.ImmediateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MemoryMachineAssemblyParser.accessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccessor([NotNull] MemoryMachineAssemblyParser.AccessorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MemoryMachineAssemblyParser.accessor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccessor([NotNull] MemoryMachineAssemblyParser.AccessorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="MemoryMachineAssemblyParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndex([NotNull] MemoryMachineAssemblyParser.IndexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="MemoryMachineAssemblyParser.index"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndex([NotNull] MemoryMachineAssemblyParser.IndexContext context);
}
} // namespace MemoryMachine.Core.Parser
