[tools]
dotnet = "9.0.102"
uv = "latest"
"cargo:ouch" = "latest"
"pipx:antlr4-tools" = "latest"

[tasks]
"c:run" = "dotnet run --project src/MemoryMachine.Console"
build = "dotnet build"
tar = "ouch c . ram.tar.gz -g"
