min_version = "2024.1.1"

[tools]
cargo-binstall         = "1.10.17"
"cargo:bacon"          = "latest"
"cargo:cargo-deny"     = "latest"
"cargo:cargo-dist"     = "latest"
"cargo:cargo-edit"     = "latest"
"cargo:cargo-feature"  = "latest"
"cargo:cargo-generate" = "latest"
"cargo:cargo-insta"    = "latest"
"cargo:cargo-nextest"  = "latest"
"cargo:cargo-shear"    = "latest"
"cargo:cargo-show"     = "latest"
"cargo:cross"          = "latest"
"cargo:flamegraph"     = "latest"
"cargo:git-cliff"      = "latest"
"cargo:just"           = "latest"
"cargo:ouch"           = "latest"
"cargo:toml-cli"       = "latest"
"cargo:typos-cli"      = "latest"
"cargo:wasm-tools"     = "latest"
jq                     = "latest"
just                   = "latest"
"pipx:antlr4-tools"    = "latest"
taplo                  = "latest"
