[package]
name = "ram_diagnostics"

authors.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
version.workspace    = true

[dependencies]
miette    = { workspace = true }
thiserror = { workspace = true }

ram_error = { workspace = true }
